//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendSMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SendSMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Female {
            get {
                object obj = ResourceManager.GetObject("Female", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Августа
        ///Авдотья
        ///Авелина
        ///Аврелия
        ///Аврора
        ///Агапия
        ///Агата
        ///Агафия
        ///Агафья
        ///Аглаида
        ///Аглая
        ///Агнеса
        ///Агния
        ///Аграфена
        ///Агриппина
        ///Ада
        ///Аделаида
        ///Адель
        ///Аза
        ///Азалия
        ///Аида
        ///Айша
        ///Акилина
        ///Аксинья
        ///Акулина
        ///Алевтина
        ///Аля  
        ///Александра
        ///Алена
        ///Алина
        ///Алиса
        ///Алла
        ///Альба
        ///Альберта
        ///Альбина
        ///Альда
        ///Альфия
        ///Альма
        ///Алёна
        ///Амалия
        ///Анастасия
        ///Настя
        ///Анатолия
        ///Ангелина
        ///Анжела
        ///Анимаиса
        ///Анисия
        ///Анита
        ///Анна 
        ///Аня
        ///Антонида
        ///Антонина 
        ///Тоня
        ///Антония
        ///Антуанетта
        ///Анфиса
        ///Анфия
        ///Аполлинария
        ///Апраксия
        ///Арабелла
        ///Ариадна
        ///Арина
        ///Аркадия
        ///Арсения
        ///Артемия
        ///Аспазия
        ///Аста
        ///Астра
        ///Астрид
        ///Афанасия
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Male {
            get {
                object obj = ResourceManager.GetObject("Male", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абрам
        ///Авангард
        ///Аввакум
        ///Август
        ///Августин
        ///Авдей
        ///Авенир
        ///Аверкий
        ///Авксентий
        ///Авраам
        ///Аврелий
        ///Аврор
        ///Автоном
        ///Агап
        ///Агафон
        ///Агей
        ///Адам
        ///Адий
        ///Адольф
        ///Адонис
        ///Адриан
        ///Аким
        ///Акинфий
        ///Аксен
        ///Аксён
        ///Алан
        ///Алар
        ///Алевтин
        ///Александр
        ///Алексей
        ///Леша
        ///Ален
        ///Алим
        ///Альберт
        ///Альбин
        ///Альварес
        ///Альвиан
        ///Альвин
        ///Альфонс
        ///Альфред
        ///Амадей
        ///Амвросий
        ///Амин
        ///Амос
        ///Ананий
        ///Анастасий
        ///Анатолий
        ///Толя
        ///Анвар
        ///Ангел
        ///Андрей
        ///Андриан
        ///Андрон
        ///Анемподист
        ///Анис
        ///Анисим
        ///Анри
        ///Антей
        ///Антип
        ///Антон
        ///Антонин
        ///Антуан
        ///Анфим
        ///Аполлинарий
        ///Аполлон
        ///Арам
        ///Арвид
        ///Аргент
        ///Арефа
        ///Арефий
        ///Арий
        ///Аристарх
        ///Аркадий
        ///Арк [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unknown {
            get {
                object obj = ResourceManager.GetObject("Unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
